Отчет по лабораторной работе №7
Retofu/MeasurementProcessSoftware pull request #10
Opened 2023-11-30 16:19 UTC by Retofu

2023-12-02 07:27 UTC, lamer0k requested changes

2023-12-02 07:27 UTC, lamer0k commented on Lab7/Lab7.adoc
> +  const auto timerValue = static_cast<std::uint32_t>(period * (TIM2Clock / 1000U - 1U)) ;
Если у нас задержка в мс, то надо просто поставить делитель такой, чтобы каждый тик таймера был через 1 мс. Например, если частота 8 000 000, то в PSC регистр надо записать 8000. Надо завести константу для деления типа MsPrescaler  и записать его в регистр PCS, тогда в ARR надо будет записывать period.

Я так понял ты сделал в микросекундах,

2023-12-02 07:27 UTC, lamer0k commented on Lab7/Lab7.adoc
> +  while (TIM2::SR::UIF::Get() == 0)
0 надо привести к типу, который возвращает Get(). иначе типы разные, это  как сравнить теплое с мягким.

2023-12-07 15:59 UTC, Retofu commented on Lab7/Lab7.adoc
> +  while (TIM2::SR::UIF::Get() == 0)
Исправил

2023-12-07 15:59 UTC, Retofu commented on Lab7/Lab7.adoc
> +  const auto timerValue = static_cast<std::uint32_t>(period * (TIM2Clock / 1000U - 1U)) ;
Исправил

2023-12-16 09:40 UTC, lamer0k approved these changes

2023-12-16 10:22 UTC, merged