Отчет по лабораторной работе №9
Retofu/MeasurementProcessSoftware pull request #12
Opened 2023-12-21 18:25 UTC by Retofu

2023-12-21 18:26 UTC, Retofu commented
Программа пока что не работает, не могу понять где ошибки.

2023-12-22 17:47 UTC, lamer0k requested changes

2023-12-22 17:47 UTC, lamer0k commented on Lab9/Lab9.adoc
> +      allflickMode.SetTimerFlag(false);
Зачем тут скидываем? В итоге при выходе из прерывания, у нас будет скинутый флажок.

2023-12-22 17:47 UTC, lamer0k commented on Lab9/Lab9.adoc
> +      allflickMode.Update();
После этого скинь флажок.

2023-12-22 18:11 UTC, lamer0k commented on Lab9/Lab9.adoc
> +      allflickMode.SetTimerFlag(false);
Кстати, сразу метод переименуй. Почему SetTimerFlag? Почему таймер? Ты сразу привязываешься к таймеру, но названия метода ни о чем не говорит, почему я должен что-то делать когда TimerFlag установлен, какое вообще отношение Timer имеет к allFlickMode или кнопкам?
Метод должен называтья а) Абстрактно б) говорить для чего он предназначен. В данном случае метод преднназначен для того, чтобы начать Update гирлянды. Поэтому он и должен называться что-то типа: IsUpdateNeeded() или CheckForUpdate()? Типа надо ли обновляться  или проверить на необходимость обновления?  Он кстати сразу может сам скинуть флажок, чтобы в мейне не было лишнего непонятного кода.

2023-12-22 18:11 UTC, lamer0k commented on Lab9/Lab9.adoc
> +      allflickMode.Update();
Кстати, сразу метод переименуй. Почему GetTimerFlag? Почему таймер? Ты сразу привязываешься к таймеру, но названия метода ни о чем не говорит, почему я должен что-то делать когда TimerFlag установлен, какое вообще отношение Timer имеет к allFlickMode или кнопкам?
Метод должен называтья а) Абстрактно б) говорить для чего он предназначен. В данном случае метод преднназначен для того, чтобы начать Update гирлянды. Поэтому он и должен называться что-то типа: IsUpdateNeeded() или CheckForUpdate()? Типа надо ли обновляться  или проверить на необходимость обновления?  Он кстати сразу может сам скинуть флажок, чтобы в мейне не было лишнего непонятного кода.

2023-12-22 19:30 UTC, Retofu commented on Lab9/Lab9.adoc
> +      allflickMode.SetTimerFlag(false);
Поменял

2023-12-22 19:34 UTC, Retofu commented on Lab9/Lab9.adoc
> +      allflickMode.Update();
Поменял, сделал пока без отдельного интерфейса.
Программа всё равно не работает, после нажатия Download and Debug возможно нажать только на паузу. Там программа сразу попадает в startupF411RE.cpp в бесконечный цикл в:
void DummyModule::handler()   { for(;;) {} } ;

2023-12-22 19:37 UTC, Retofu commented on Lab9/Lab9.adoc
> +      allflickMode.Update();
Я уже перепроверял по таблице, таймеры в стартапе поставлены в правильных строчках. И в main.cpp разрешения глобальных прерываний тоже вроде должны быть правильные.
Возможно такое, что при настройке таймеров нужно ставить эти команды в определенном порядке?

2023-12-22 19:44 UTC, lamer0k commented on Lab9/Lab9.adoc
> +      allflickMode.Update();
Если падает в бесконечный цикл, значит проблем может быть несколько
1. Неправильный вектор прерывания - проверяй, точно ли в тот попадает.Чтобы проверить, можно по паузе посмотреть регистры ( не помню какой, как раз задача найди в интернете) который показывает в каком векторе прерывания сейчас находимся. Там такой регистр точно есть.  Ну либо делай на каждое прерывание свой обработчик.
2. Какая-то ошибка, которую микроконтроллер не может обработать, например, стек переполнился например и вызвалось прерывание по Ошибке.

Все больше вариантов нет :)

2023-12-23 07:39 UTC, Retofu commented on Lab9/Lab9.adoc
> +      allflickMode.Update();
Нашел описание регистров (https://mcucpu.ru/index.php/platformy-32-bit/stm32/150-preryvaniya-v-stm32).
![image](https://github.com/Retofu/MeasurementProcessSoftware/assets/144712150/80035e32-df34-4494-8c62-43bc179dc148)
Получается, что мы записываем в ISER разрешения прерываний, программа сама записывает в ICER сброс этих разрешений. В итоге в IABR активных нет.
Попытался записать в ICER нули, чтобы не сбрасывались разрешения, не помогло.

2023-12-23 07:50 UTC, lamer0k commented on Lab9/Lab9.adoc
> +      allflickMode.Update();
Смотри, когда ты завис, ты попал в DummyHandler нажми на паузу.
Чтобы определить в каком ты прерывания есть регистр IABR, по  его значению можешь понять какое прерывание случается И там дальше уже поймёшь, что происходит.

2023-12-23 07:52 UTC, lamer0k commented on Lab9/Lab9.adoc
> +      allflickMode.Update();
Если когда ты попал в DummyHandler нет активных IABR, то ты скорее всего попал в обработчик какой то ошибки. Тогда смотри стек вызова, что до этого выщывалось и откуда он попал в это прерывание

2023-12-23 07:55 UTC, Retofu commented on Lab9/Lab9.adoc
> +      allflickMode.Update();
Хорошо, проверю

2023-12-24 13:39 UTC, Retofu commented on Lab9/Lab9.adoc
> +      allflickMode.Update();
Исправил

2024-03-20 18:16 UTC, merged