Курсовой проект
Retofu/MeasurementProcessSoftware pull request #13
Opened 2024-02-22 15:57 UTC by Retofu

2024-03-07 13:47 UTC, lamer0k commented on Coursework/Poyasnitelnaya Zapiska.adoc
> +stem:["AdcVoltageValue" = ("AdcCodeValue" * "MaxVoltage") / "MaxAdcCode"], +
А точно такой формулы хватит для точности 0.01В?

2024-03-07 13:57 UTC, lamer0k commented on Coursework/Poyasnitelnaya Zapiska.adoc
> +stem:["AdcVoltageValue" = ("AdcCodeValue" * "MaxVoltage") / "MaxAdcCode"], +
хочу чтобы от 0 до 5% все светодиоды тушились.

2024-03-07 13:58 UTC, lamer0k commented on Coursework/Poyasnitelnaya Zapiska.adoc
> +В требованиях указан период измерения 50 мс, при этом цифровой фильтр должен работать с периодом 100 мс, что является не логичным. Поэтому следует увеличить период измерения до 100 мс или уменьшить п
Согласовали 50мс

2024-03-07 14:02 UTC, lamer0k requested changes
Пару замечаний
1. Описать фильтр, как задается постоянная времени, пока взять 1секунду по умолчанию.
2. Описать, как точность обеспечить (калибровкой с помощью прецензионного вольтметра)

2024-03-09 11:25 UTC, Retofu commented on Coursework/Poyasnitelnaya Zapiska.adoc
> +stem:["AdcVoltageValue" = ("AdcCodeValue" * "MaxVoltage") / "MaxAdcCode"], +
Дописал ниже

2024-03-09 11:25 UTC, Retofu commented on Coursework/Poyasnitelnaya Zapiska.adoc
> +stem:["AdcVoltageValue" = ("AdcCodeValue" * "MaxVoltage") / "MaxAdcCode"], +
Дописал в анализе требований

2024-03-09 11:26 UTC, Retofu commented on Coursework/Poyasnitelnaya Zapiska.adoc
> +В требованиях указан период измерения 50 мс, при этом цифровой фильтр должен работать с периодом 100 мс, что является не логичным. Поэтому следует увеличить период измерения до 100 мс или уменьшить п
Написал

2024-03-09 11:54 UTC, lamer0k commented on Coursework/Poyasnitelnaya Zapiska.adoc
> +stem:["AdcVoltageValue" = ("AdcCodeValue" * "MaxVoltage") / "MaxAdcCode"], +
Надо формулу с калибровкой написать уже. Будет две точки калибровки верхняя и нижняя. Они должны участвовать в формуле.

2024-03-13 18:41 UTC, Retofu commented on Coursework/Poyasnitelnaya Zapiska.adoc
> +stem:["AdcVoltageValue" = ("AdcCodeValue" * "MaxVoltage") / "MaxAdcCode"], +
Написал

2024-03-14 14:59 UTC, lamer0k commented on Coursework/Poyasnitelnaya Zapiska.adoc
> +stem:["LEDsAmount" = ⌈("AdcVoltageValue" * "MaxLEDsAmount") / "MaxCalibrVoltage"⌉], +
b коэффициент пропал.

2024-03-16 09:38 UTC, Retofu commented on Coursework/Poyasnitelnaya Zapiska.adoc
> +stem:["LEDsAmount" = ⌈("AdcVoltageValue" * "MaxLEDsAmount") / "MaxCalibrVoltage"⌉], +
добавил

2024-03-16 12:15 UTC, Retofu commented on Coursework/Poyasnitelnaya Zapiska.adoc
> +stem:["LEDsAmount" = ⌈("AdcVoltageValue" * "MaxLEDsAmount") / "MaxCalibrVoltage"⌉], +
Исправил

2024-03-16 14:30 UTC, lamer0k approved these changes

2024-03-16 14:32 UTC, merged