Добавление детальной архитектуры и классов MeasurementTask, DigitalFilter, Voltage
Retofu/MeasurementProcessSoftware pull request #15
Opened 2024-04-13 12:34 UTC by Retofu

2024-04-20 11:34 UTC, lamer0k commented on Coursework/source/RtosWrapper/Application/DigitalFilter/digitalfilter.h
> +class DigitalFilter : public tIFilter
сделать шаблонным куда передать rc и dt

2024-04-20 11:37 UTC, lamer0k commented on Coursework/source/RtosWrapper/Application/DigitalFilter/digitalfilter.h
> +class DigitalFilter : public tIFilter
Название поменять на DigitalFloatFilter

2024-04-20 11:40 UTC, lamer0k commented on Coursework/source/RtosWrapper/Application/DigitalFilter/digitalfilter.h
> +  const std::float_t tau = 0.95f;
сделать тут расчет

2024-04-20 11:47 UTC, lamer0k commented on Coursework/source/RtosWrapper/Application/Tasks/measurementtask.cpp
> +void MeasurementTask<>::Execute()
убрать в h файл

2024-04-20 11:47 UTC, lamer0k commented on Coursework/source/RtosWrapper/Application/Tasks/measurementtask.cpp
> +    volatile auto filteredVoltage = _filteredValue.FilterValue(measurementVariable);
TODO поставить.

2024-04-20 11:48 UTC, lamer0k commented on Coursework/source/RtosWrapper/Application/Tasks/measurementtask.h
> +template<auto& event>
удалить евент.

2024-04-20 11:50 UTC, lamer0k commented on Coursework/source/RtosWrapper/main.cpp
> +#include "event.hpp"        // for Event
Удалить все что не надо.

2024-04-20 11:54 UTC, lamer0k commented on Coursework/source/RtosWrapper/main.cpp
> +
удалить.

2024-04-20 11:55 UTC, lamer0k commented on Coursework/source/RtosWrapper/main.cpp
> +    //Switch on internal 16 MHz oscillator
Неправильный комментарий

2024-04-20 11:56 UTC, lamer0k commented on Coursework/source/RtosWrapper/main.cpp
> +    USART2::CR1::UE::Enable::Set();
удалить

2024-04-20 11:56 UTC, lamer0k commented on Coursework/source/RtosWrapper/main.cpp
> +//  std::float_t tempValueWithCalibration = 0.0f;
удалить

2024-04-20 11:56 UTC, lamer0k commented on Coursework/source/RtosWrapper/main.cpp
> +//}
удалить

2024-04-20 11:56 UTC, lamer0k commented on Coursework/source/RtosWrapper/main.cpp
> +//  }
удалить

2024-04-20 11:57 UTC, lamer0k commented on Coursework/source/RtosWrapper/main.cpp
> +  Rtos::CreateThread(bluetoothTask, "BluetoothTask", ThreadPriority::lowest);
удалить

2024-04-20 11:57 UTC, lamer0k requested changes
Поправить надо

2024-04-23 12:51 UTC, Retofu commented on Coursework/source/RtosWrapper/Application/DigitalFilter/digitalfilter.h
> +class DigitalFilter : public tIFilter
Исправил

2024-04-23 12:52 UTC, Retofu commented on Coursework/source/RtosWrapper/Application/DigitalFilter/digitalfilter.h
> +class DigitalFilter : public tIFilter
Поменял

2024-04-23 12:52 UTC, Retofu commented on Coursework/source/RtosWrapper/Application/DigitalFilter/digitalfilter.h
> +  const std::float_t tau = 0.95f;
Добавил расчет

2024-04-23 12:52 UTC, Retofu commented on Coursework/source/RtosWrapper/Application/Tasks/measurementtask.cpp
> +    volatile auto filteredVoltage = _filteredValue.FilterValue(measurementVariable);
Добавил

2024-04-23 12:52 UTC, Retofu commented on Coursework/source/RtosWrapper/Application/Tasks/measurementtask.h
> +template<auto& event>
Удалил

2024-04-23 12:52 UTC, Retofu commented on Coursework/source/RtosWrapper/main.cpp
> +#include "event.hpp"        // for Event
Удалил лишнее

2024-04-23 12:52 UTC, Retofu commented on Coursework/source/RtosWrapper/main.cpp
> +
Удалил

2024-04-23 12:52 UTC, Retofu commented on Coursework/source/RtosWrapper/main.cpp
> +    //Switch on internal 16 MHz oscillator
Исправил

2024-04-23 12:52 UTC, Retofu commented on Coursework/source/RtosWrapper/main.cpp
> +    USART2::CR1::UE::Enable::Set();
Убрал

2024-04-23 12:53 UTC, Retofu commented on Coursework/source/RtosWrapper/main.cpp
> +//  std::float_t tempValueWithCalibration = 0.0f;
Удалил

2024-04-23 12:53 UTC, Retofu commented on Coursework/source/RtosWrapper/main.cpp
> +//}
убрал

2024-04-23 12:53 UTC, Retofu commented on Coursework/source/RtosWrapper/main.cpp
> +//  }
удалил

2024-04-23 12:53 UTC, Retofu commented on Coursework/source/RtosWrapper/main.cpp
> +  Rtos::CreateThread(bluetoothTask, "BluetoothTask", ThreadPriority::lowest);
убрал лишнее

2024-04-23 12:54 UTC, Retofu commented on Coursework/source/RtosWrapper/main.cpp
> +//}
убрал

2024-04-23 14:47 UTC, lamer0k commented on Coursework/source/RtosWrapper/main.cpp
> +DigitalFilter<float, 5, 2> digitalFloatFilter;
не тот класс.

2024-04-23 14:50 UTC, lamer0k commented on Coursework/source/RtosWrapper/main.cpp
> +    while (RCC::CR::HSERDY::NotReady::IsSet())
внешний генератор на 8 Мгц.

2024-04-23 16:10 UTC, Retofu commented on Coursework/source/RtosWrapper/main.cpp
> +    while (RCC::CR::HSERDY::NotReady::IsSet())
Исправил

2024-04-27 13:28 UTC, lamer0k approved these changes

2024-04-27 13:31 UTC, merged