Добавление классов IMeasurementVariable, Voltage, IDataProvider. Небольшое исправление предыдущих классов
Retofu/MeasurementProcessSoftware pull request #16
Opened 2024-04-27 15:30 UTC by Retofu

2024-04-27 15:59 UTC, lamer0k commented on Coursework/source/RtosWrapper/Application/Measurement/voltage.h
> +  const float gain = (3.2999 - 0.0001) / (4095.0 - 2.0) ;
Надо убирать из класса в коснтруктор или в шаблон

2024-04-27 16:00 UTC, lamer0k commented on Coursework/source/RtosWrapper/Application/Measurement/voltage.h
> +//  float Measure() // TODO: in next PR
std::cout <<  чтобы проверить, что все работает.

2024-04-27 16:02 UTC, lamer0k commented on Coursework/source/RtosWrapper/Application/Measurement/voltage.h
> +    auto voltageValue = gain * data + offset;
data.GetData()

2024-04-27 16:04 UTC, lamer0k commented on Coursework/source/RtosWrapper/Application/Measurement/voltage.h
> +  float Voltage(IDataProvider& data) override
Перенсти все в метод Measure()

2024-04-27 16:05 UTC, lamer0k commented on Coursework/source/RtosWrapper/Application/Measurement/voltage.h
> +  IDataProvider& data;
mData

2024-04-27 16:06 UTC, lamer0k commented on Coursework/source/RtosWrapper/Application/Measurement/voltage.h
> +  float Voltage(IDataProvider& data) override
Контструктор должен только ингициализировать атрибуты класс: 

Voltage(IDataProvider& data) : mData(data)
{
}

2024-04-27 16:06 UTC, lamer0k commented on Coursework/source/RtosWrapper/Application/DigitalFilter/digitalfilter.h
> +  const std::float_t tau = 1 - exp(- dt / rc);
static constexpr

2024-04-27 16:09 UTC, lamer0k requested changes
Надо переделать, чтобы компилилось

2024-04-30 16:09 UTC, Retofu commented on Coursework/source/RtosWrapper/Application/Measurement/voltage.h
> +  const float gain = (3.2999 - 0.0001) / (4095.0 - 2.0) ;
Поменял

2024-04-30 16:09 UTC, Retofu commented on Coursework/source/RtosWrapper/Application/Measurement/voltage.h
> +//  float Measure() // TODO: in next PR
Добавил

2024-04-30 16:09 UTC, Retofu commented on Coursework/source/RtosWrapper/Application/Measurement/voltage.h
> +    auto voltageValue = gain * data + offset;
Исправил

2024-04-30 16:09 UTC, Retofu commented on Coursework/source/RtosWrapper/Application/Measurement/voltage.h
> +  float Voltage(IDataProvider& data) override
Перенес

2024-04-30 16:09 UTC, Retofu commented on Coursework/source/RtosWrapper/Application/Measurement/voltage.h
> +  IDataProvider& data;
Исправил

2024-04-30 16:10 UTC, Retofu commented on Coursework/source/RtosWrapper/Application/Measurement/voltage.h
> +  float Voltage(IDataProvider& data) override
Добавил конструктор

2024-04-30 16:11 UTC, Retofu commented on Coursework/source/RtosWrapper/Application/DigitalFilter/digitalfilter.h
> +  const std::float_t tau = 1 - exp(- dt / rc);
Не будет исправлено, так как есть exp

2024-05-04 11:43 UTC, lamer0k approved these changes

2024-05-04 11:57 UTC, merged