Добавление класса AdcDmaDataProvider, обновление IDataProvider. Обновление дизайна
Retofu/MeasurementProcessSoftware pull request #17
Opened 2024-05-04 13:43 UTC by Retofu

2024-05-04 13:52 UTC, lamer0k commented on Coursework/source/RtosWrapper/Application/Measurement/idataprovider.h
> +  virtual void ConfigAdc() const = 0;
Убрать отсюда. Интерфейс отвечает только за получение данных.

2024-05-04 13:54 UTC, lamer0k commented on Coursework/source/RtosWrapper/AHardware/ADC/adcdmadataprovider.h
> +    ADC1::CR1::RES::Bits12::Set();
Можно сделать в LowLevelInit, можно в конструкторе этого класса, можно сделать отдельный интерфейс для настройки.

2024-05-04 13:55 UTC, lamer0k commented on Coursework/source/RtosWrapper/AHardware/ADC/adcdmadataprovider.h
> +  void ConfigAdc()
Разделить класс на h и cpp

2024-05-04 13:56 UTC, lamer0k commented on Coursework/source/RtosWrapper/AHardware/ADC/adcdmadataprovider.h
> +  }
Приватный атрбиут нужен для хранения кода АЦП.

2024-05-04 13:57 UTC, lamer0k commented on Coursework/source/RtosWrapper/main.cpp
> +//Voltage<offset, gain> voltage; // TODO
Создать объект AdcDataProvider и передать в конструктор Voltage.

2024-05-04 13:57 UTC, lamer0k requested changes
Надо переделать все и сделать, чтобы работало все с DMA

2024-05-14 13:54 UTC, Retofu commented on Coursework/source/RtosWrapper/AHardware/ADC/adcdmadataprovider.h
> +  void ConfigAdc()
Разделил

2024-05-14 16:04 UTC, Retofu commented on Coursework/source/RtosWrapper/main.cpp
> +//Voltage<offset, gain> voltage; // TODO
Добавил

2024-05-14 16:04 UTC, Retofu commented on Coursework/source/RtosWrapper/AHardware/ADC/adcdmadataprovider.h
> +    ADC1::CR1::RES::Bits12::Set();
Сделал

2024-05-14 16:04 UTC, Retofu commented on Coursework/source/RtosWrapper/Application/Measurement/idataprovider.h
> +  virtual void ConfigAdc() const = 0;
Убрал

2024-05-14 16:05 UTC, Retofu commented on Coursework/source/RtosWrapper/AHardware/ADC/adcdmadataprovider.h
> +  }
Добавил

2024-05-18 13:47 UTC, lamer0k commented on Coursework/source/RtosWrapper/main.cpp
> +Voltage<offset, gain> voltage(static_cast<IDataProvider&>(adc)); // TODO
Что за TODO?

2024-05-18 13:51 UTC, lamer0k commented on Coursework/source/RtosWrapper/AHardware/ADC/adcdmadataprovider.cpp
> +  DMA2::S0NDTR::Write(1);
Что это?

2024-05-18 16:04 UTC, Retofu commented on Coursework/source/RtosWrapper/AHardware/ADC/adcdmadataprovider.cpp
> +  DMA2::S0NDTR::Write(1);
Добавил описание

2024-05-18 16:04 UTC, Retofu commented on Coursework/source/RtosWrapper/main.cpp
> +Voltage<offset, gain> voltage(static_cast<IDataProvider&>(adc)); // TODO
Убрал

2024-05-28 13:29 UTC, lamer0k approved these changes

2024-05-28 13:30 UTC, merged