Отчет №3 "Указатели и ссылки"
Retofu/MeasurementProcessSoftware pull request #4
Opened 2023-10-12 14:28 UTC by Retofu

2023-10-12 15:14 UTC, lamer0k commented on Report3.adoc
> +Чтобы определить указатель на константу, он тоже должен объявляться через "const", как и константа. Изменить значение по адресу, который хранится в указателе на константу, не рекомендуется, так как б
изменять значение по адресу, чисто теоритически можно, я как раз это показывал, что можно убрать константность, и ошибки компиляции не будет, но делать действительно не надо, потому что при выполнении программы может быть Undefined Behaviour, например, попытка поменять значение перменной лежащей во Flash

2023-10-12 15:19 UTC, lamer0k approved these changes

2023-10-12 15:19 UTC, lamer0k commented on Report3.adoc
> +* у ссылки нельзя взять адрес. Если применить оператор взятия адреса к ней, то будет выведен адрес переменной, на которую она ссылается;
А если взять адрес у указателя, что будет?

2023-10-12 16:36 UTC, Retofu commented on Report3.adoc
> +Чтобы определить указатель на константу, он тоже должен объявляться через "const", как и константа. Изменить значение по адресу, который хранится в указателе на константу, не рекомендуется, так как б
Исправил

2023-10-12 16:37 UTC, Retofu commented on Report3.adoc
> +* у ссылки нельзя взять адрес. Если применить оператор взятия адреса к ней, то будет выведен адрес переменной, на которую она ссылается;
Исправил

2023-10-12 16:48 UTC, lamer0k approved these changes

2023-10-12 16:48 UTC, lamer0k commented on Report3.adoc
> +* у ссылки нельзя взять адрес. Если применить оператор взятия адреса к ней, то будет выведена созданная компилятором переменная, в которой есть адрес, но для пользователя у ссылки адреса не существуе
Не было то правильнло, я просто вопрос задал про что будет если взять адрес у указателя? ПРосто добавь ответ на вопрос, а тут верни. Все верно

2023-10-12 16:48 UTC, lamer0k commented on Report3.adoc
> +* у ссылки нельзя взять адрес. Если применить оператор взятия адреса к ней, то будет выведена созданная компилятором переменная, в которой есть адрес, но для пользователя у ссылки адреса не существуе
И слей 2 пул реквеста предыдущих, что они у тебя весят?

2023-10-12 17:07 UTC, Retofu commented on Report3.adoc
> +* у ссылки нельзя взять адрес. Если применить оператор взятия адреса к ней, то будет выведена созданная компилятором переменная, в которой есть адрес, но для пользователя у ссылки адреса не существуе
Хорошо, сейчас исправлю
По лабе №1 я исправил оглавление, поэтому ждал ещё раз аппрува, а Отчет №2 "Типы данных" не отмечен как проверенный

2023-10-13 15:47 UTC, Retofu commented on Report3.adoc
> +* у ссылки нельзя взять адрес. Если применить оператор взятия адреса к ней, то будет выведена созданная компилятором переменная, в которой есть адрес, но для пользователя у ссылки адреса не существуе
Добавил

2023-10-14 12:45 UTC, lamer0k requested changes

2023-10-14 12:45 UTC, lamer0k commented on Report3.adoc
> +:toc: macro
тест

2023-10-17 18:05 UTC, Retofu commented on Report3.adoc
> +:toc: macro
тест

2023-10-20 19:20 UTC, lamer0k commented on Report3.adoc
> +Указатели можно складывать, вычитать, сравнивать, но указатели должны быть одного типа. Также у указателя можно взять адрес, который будет являться адресом переменной, связанной с этим указателем.
складывать и вычитать с целым числом.

2023-10-21 06:47 UTC, Retofu commented on Report3.adoc
> +Указатели можно складывать, вычитать, сравнивать, но указатели должны быть одного типа. Также у указателя можно взять адрес, который будет являться адресом переменной, связанной с этим указателем.
Исправил

2023-10-21 08:59 UTC, lamer0k approved these changes

2023-10-21 09:02 UTC, merged