Отчет по лабораторной работе №3
Retofu/MeasurementProcessSoftware pull request #6
Opened 2023-10-26 17:26 UTC by Retofu

2023-10-28 07:43 UTC, lamer0k requested changes

2023-10-28 07:43 UTC, lamer0k commented on Lab3/Lab3.adoc
> +
еще такой пример можно использовать:
char a = (std::cout << "Определяю переменную" << std::endl , 4);
Здесь вначале выведется сообщение, а затем a присвоится 4:
но оператор запятая использовать не надо - это зло. Усложняет понимание программы.

2023-10-28 07:43 UTC, lamer0k commented on Lab3/Lab3.adoc
> +* логические операторы;
про унарный плюс не написал

2023-10-28 07:43 UTC, lamer0k commented on Lab3/Lab3.adoc
> +Используя формулу для расчета частоты, нужно подобрать только соответствующие коэффициенты. Возьмем коэффициенты: PLLN = 64, PLLM = 16, PLLP = 2. Подставим коэффициенты в формулу:
Там еще есть условия для FCO, их почему не проверил?

2023-10-28 07:43 UTC, lamer0k commented on Lab3/Lab3.adoc
> +    *reinterpret_cast<std::uint32_t*>(0x40023804) |= (1U << 4U);
Да там в обертке нет PLLM , но это можно поправить, добавить определение для PLLM


`
  struct PLLCFGR : public RegisterBase<0x40023804, 32, ReadWriteMode>
  {
    using PLLQ0 = RCC_PLLCFGR_PLLQ_Values<RCC::PLLCFGR, 24, 4, ReadWriteMode, RCCPLLCFGRBase> ;
    using PLLSRC = RCC_PLLCFGR_PLLSRC_Values<RCC::PLLCFGR, 22, 1, ReadWriteMode, RCCPLLCFGRBase> ;
    using PLLP0 = RCC_PLLCFGR_PLLP_Values<RCC::PLLCFGR, 16, 2, ReadWriteMode, RCCPLLCFGRBase> ;
    using PLLN0 = RCC_PLLCFGR_PLLN_Values<RCC::PLLCFGR, 6, 9, ReadWriteMode, RCCPLLCFGRBase> ;
    using FieldValues = RCC_PLLCFGR_PLLM_Values<RCC::PLLCFGR, 0, 5, NoAccess, NoAccess> ;
  } ;
`
надо поменять на 
`
  struct PLLCFGR : public RegisterBase<0x40023804, 32, ReadWriteMode>
  {
    using PLLQ0 = RCC_PLLCFGR_PLLQ_Values<RCC::PLLCFGR, 24, 4, ReadWriteMode, RCCPLLCFGRBase> ;
    using PLLSRC = RCC_PLLCFGR_PLLSRC_Values<RCC::PLLCFGR, 22, 1, ReadWriteMode, RCCPLLCFGRBase> ;
    using PLLP0 = RCC_PLLCFGR_PLLP_Values<RCC::PLLCFGR, 16, 2, ReadWriteMode, RCCPLLCFGRBase> ;
    using PLLN0 = RCC_PLLCFGR_PLLN_Values<RCC::PLLCFGR, 6, 9, ReadWriteMode, RCCPLLCFGRBase> ;
    using PLLM0 = RCC_PLLCFGR_PLLM_Values<RCC::PLLCFGR, 0, 5, ReadWriteMode, RCCPLLCFGRBase> ;
   using FieldValues = RCC_PLLCFGR_PLLM_Values<RCC::PLLCFGR, 0, 0, NoAccess, NoAccess> ;
  } ;
`

2023-10-28 07:43 UTC, lamer0k commented on Lab3/Lab3.adoc
> +    *reinterpret_cast<std::uint32_t*>(0x40023804) |= (1U << 12U);
RCC::PLLCFGR::write(1U << 12U);

2023-10-28 08:28 UTC, Retofu commented on Lab3/Lab3.adoc
> +Используя формулу для расчета частоты, нужно подобрать только соответствующие коэффициенты. Возьмем коэффициенты: PLLN = 64, PLLM = 16, PLLP = 2. Подставим коэффициенты в формулу:
Условие для VCO clock (формула 1) я подставил в формулу 2 для PLL general clock output и получил выражение​:
f = f(PLL clock input) × (PLLN / PLLM) /PLLP​
Скрин из документации:
![1](https://github.com/Retofu/MeasurementProcessSoftware/assets/144712150/e1147f67-ce1f-4693-a204-0a26879afd6b)

2023-10-28 08:41 UTC, Retofu commented on Lab3/Lab3.adoc
> +
Добавил

2023-10-28 08:41 UTC, Retofu commented on Lab3/Lab3.adoc
> +* логические операторы;
Добавил

2023-10-28 08:41 UTC, Retofu commented on Lab3/Lab3.adoc
> +    *reinterpret_cast<std::uint32_t*>(0x40023804) |= (1U << 4U);
Поменял

2023-10-28 08:42 UTC, Retofu commented on Lab3/Lab3.adoc
> +    *reinterpret_cast<std::uint32_t*>(0x40023804) |= (1U << 12U);
Выдаёт ошибку на данную команду:
![2](https://github.com/Retofu/MeasurementProcessSoftware/assets/144712150/e389f7d6-17ca-4afb-a3d1-0579afd4c3b2)

2023-11-04 08:37 UTC, lamer0k commented on Lab3/Lab3.adoc
> +Используя формулу для расчета частоты, нужно подобрать только соответствующие коэффициенты. Возьмем коэффициенты: PLLN = 64, PLLM = 16, PLLP = 2. Подставим коэффициенты в формулу:
неа, там еще есть условия....

2023-11-04 08:37 UTC, lamer0k commented on Lab3/Lab3.adoc
> +    *reinterpret_cast<std::uint32_t*>(0x40023804) |= (1U << 12U);
Там наверное Write с большой буквы.

2023-11-04 08:51 UTC, Retofu commented on Lab3/Lab3.adoc
> +Используя формулу для расчета частоты, нужно подобрать только соответствующие коэффициенты. Возьмем коэффициенты: PLLN = 64, PLLM = 16, PLLP = 2. Подставим коэффициенты в формулу:
Для VCO clock я нашел только эти условия:
![image](https://github.com/Retofu/MeasurementProcessSoftware/assets/144712150/5c7cdac0-c6d4-497e-8acf-776b3d89ee88)
![image](https://github.com/Retofu/MeasurementProcessSoftware/assets/144712150/aabdbac4-9793-4f1c-abbc-4c991335e776)

2023-11-04 17:14 UTC, Retofu commented on Lab3/Lab3.adoc
> +    *reinterpret_cast<std::uint32_t*>(0x40023804) |= (1U << 12U);
Через Write не работает корректно, поэтому оставил через бит.

2023-11-04 17:17 UTC, Retofu commented on Lab3/Lab3.adoc
> +Используя формулу для расчета частоты, нужно подобрать только соответствующие коэффициенты. Возьмем коэффициенты: PLLN = 64, PLLM = 16, PLLP = 2. Подставим коэффициенты в формулу:
Добавил условие для VCO

2023-11-11 09:05 UTC, lamer0k approved these changes

2023-11-11 09:45 UTC, merged