Отчет по лабораторной работе №5
Retofu/MeasurementProcessSoftware pull request #8
Opened 2023-11-09 17:06 UTC by Retofu

2023-11-11 09:01 UTC, lamer0k requested changes
Пару комментариев и

2023-11-11 09:01 UTC, lamer0k commented on Lab5/Lab5.adoc
> +* L (Liskov substitution Principle, принцип подстановки Барбары Лисков) - должна быть возможность вместо базового (родительского) типа (класса) подставить любой его подтип (класс-наследник), при этом
Насколько я помню, надо было про Лисков принцип рассказать, и примеры привести.

2023-11-11 09:01 UTC, lamer0k commented on Lab5/Lab5.adoc
> +=== Шахматы
Надо добавить описание задания. Что такое шахматы?  И хорошо бы еще дизайн прикреприть, чтобы понятно было.

2023-11-11 09:01 UTC, lamer0k commented on Lab5/Lab5.adoc
> +  std::uint8_t i = 0;
не надо счетчик тащить в поле класса, это должна быть локальная переменная в методе update, потому что 1. кроме этого метода, она больше нигде не используется, 2. Ее значение не надо сохранять при следующем вызове метода Update(), в отличии, например, от переменной flag.

2023-11-11 09:01 UTC, lamer0k commented on Lab5/Lab5.adoc
> +  std::uint8_t i = 0;
бегать по массиву надо переменной типа std::size_t

2023-11-11 09:01 UTC, lamer0k commented on Lab5/Lab5.adoc
> +    } else if(!flag) // четные
зачем else if? Разве у флага есть еще 3 значение?

2023-11-11 09:01 UTC, lamer0k commented on Lab5/Lab5.adoc
> +      for(i = 0; i < leds.size(); i+=2)
Надо быть уверенным, что начальное значение всех светодиодов выключено. Но это будете думать в следующей лабе.

2023-11-11 09:01 UTC, lamer0k commented on Lab5/Lab5.adoc
> +#include "pin.h"
for

2023-11-11 09:01 UTC, lamer0k commented on Lab5/Lab5.adoc
> +#include "ipin.h"
for

2023-11-11 09:01 UTC, lamer0k commented on Lab5/Lab5.adoc
> +#include <iostream>
for и нужен ли вообще?

2023-11-11 09:01 UTC, lamer0k commented on Lab5/Lab5.adoc
> +#include <array>
Зачем?

2023-11-11 09:48 UTC, Retofu commented on Lab5/Lab5.adoc
> +=== Шахматы
Описание есть под пунктом 2 в разделе "Задание", 16 строка отчета

2023-11-11 09:51 UTC, lamer0k commented on Lab5/Lab5.adoc
> +=== Шахматы
Ок, дизайн тогда на сегодняшнем задании нарисуете.

2023-11-11 09:58 UTC, Retofu commented on Lab5/Lab5.adoc
> +#include <array>
Не нужен, остался со старой версии кода, как и iostream. Исправил

2023-11-11 09:58 UTC, Retofu commented on Lab5/Lab5.adoc
> +#include <iostream>
Не нужен, остался со старой версии кода, забыл убрать. Исправил

2023-11-11 09:58 UTC, Retofu commented on Lab5/Lab5.adoc
> +#include "ipin.h"
Добавил

2023-11-11 09:58 UTC, Retofu commented on Lab5/Lab5.adoc
> +#include "pin.h"
Добавил

2023-11-11 09:58 UTC, Retofu commented on Lab5/Lab5.adoc
> +    } else if(!flag) // четные
Исправил

2023-11-11 10:14 UTC, lamer0k requested changes

2023-11-11 10:14 UTC, lamer0k commented on Lab5/Lab5.adoc
> +#include "ipin.h" // Interface for pin.h
Интерфейс не может быть для заголовочного файла, можно просто написать for IPin и уже понятно.

2023-11-11 10:29 UTC, Retofu commented on Lab5/Lab5.adoc
> +#include "ipin.h" // Interface for pin.h
Исправил

2023-11-11 10:29 UTC, Retofu commented on Lab5/Lab5.adoc
> +  std::uint8_t i = 0;
Исправил

2023-11-11 10:29 UTC, Retofu commented on Lab5/Lab5.adoc
> +* L (Liskov substitution Principle, принцип подстановки Барбары Лисков) - должна быть возможность вместо базового (родительского) типа (класса) подставить любой его подтип (класс-наследник), при этом
Дополнил

2023-12-02 07:18 UTC, lamer0k approved these changes

2023-12-02 07:21 UTC, merged