Отчет по лабораторной работе №6
Retofu/MeasurementProcessSoftware pull request #9
Opened 2023-11-17 17:39 UTC by Retofu

2023-11-18 08:57 UTC, lamer0k requested changes

2023-11-18 08:57 UTC, lamer0k commented on Lab6/Lab6.adoc
> +    *reinterpret_cast<uint32_t*>(0x40020814) = 0;
Плохо, жёсткая привязка к каким то адресам, перейдём на другую платформу и что будет тут? Так нельзя, код должен работать везде. Кроме того, ты обнуляешь весь регистр, а может там нужные биты стояли. Придумай что то другое.

2023-11-18 08:57 UTC, lamer0k commented on Lab6/Lab6.adoc
> +    *reinterpret_cast<uint32_t*>(0x40020814) = 0;
Тоже самое.

2023-11-18 08:57 UTC, lamer0k commented on Lab6/Lab6.adoc
> +    *reinterpret_cast<uint32_t*>(0x40020014) = 0;
Опять.

2023-11-18 08:57 UTC, lamer0k commented on Lab6/Lab6.adoc
> +  void delay(int cycles)
В кнопке не должно быть задержек, ты неявно затормозил программу, а если ещё  что то надо делать?

2023-11-18 08:57 UTC, lamer0k commented on Lab6/Lab6.adoc
> +    delay(500000); // задержка
Зачем?

2023-11-18 08:57 UTC, lamer0k commented on Lab6/Lab6.adoc
> +  IMode* currentMode = mod[0];
Обычно имена указателей начинаются с буквы p, например pCurrentMode

2023-11-18 08:57 UTC, lamer0k commented on Lab6/Lab6.adoc
> +TreeMode<pin1, pin2, pin3, pin4> treeMode;
Минор, можно не править. Чтобы не ошибиться со списком пином, можно сделать вспомогательный статический класс, в который передать пины, а потом во все режимы передать этот класс. Тогда список пинов будет оди и одинаковый для всех режимов.

2023-11-18 08:57 UTC, lamer0k commented on Lab6/Lab6.adoc
> +    if(button.IsPressed() == true)
True  убрать. Масло масленное.

2023-11-18 08:57 UTC, lamer0k commented on Lab6/Lab6.adoc
> +    treeMode.Clear(); //
Не надо у всех режимов тут вызывать Clerar. Перенеси это в метод NextMode.

2023-11-18 08:57 UTC, lamer0k commented on Lab6/Lab6.adoc
> +    i++;
Сразу вызов у текущего режима Clear()

2023-11-18 10:47 UTC, Retofu commented on Lab6/Lab6.adoc
> +    if(button.IsPressed() == true)
Убрал

2023-11-18 10:47 UTC, Retofu commented on Lab6/Lab6.adoc
> +  IMode* currentMode = mod[0];
Исправил

2023-11-18 10:47 UTC, Retofu commented on Lab6/Lab6.adoc
> +    delay(500000); // задержка
Убрал задержку

2023-11-18 10:47 UTC, Retofu commented on Lab6/Lab6.adoc
> +  void delay(int cycles)
Убрал задержку

2023-11-18 13:36 UTC, Retofu commented on Lab6/Lab6.adoc
> +    *reinterpret_cast<uint32_t*>(0x40020814) = 0;
Исправил

2023-11-18 13:36 UTC, Retofu commented on Lab6/Lab6.adoc
> +    treeMode.Clear(); //
Исправил

2023-11-18 13:37 UTC, Retofu commented on Lab6/Lab6.adoc
> +    i++;
Добавил

2023-12-02 07:13 UTC, lamer0k commented on Lab6/Lab6.adoc
> +    i++;
Лучше вызвать SetToDefault у нового мода, а не старого, потому что новый мод дефолтное значение должен под себя делать. Поменяй местами строчик 266 и 267 
Еще при первом вызове метода NextMode у тебя мод меняться не будет. Поэтому скорее всего i++ и проверку надо поставить перед.

2023-12-07 15:41 UTC, Retofu commented on Lab6/Lab6.adoc
> +    i++;
Исправил

2023-12-16 09:39 UTC, lamer0k approved these changes

2023-12-16 10:21 UTC, merged